// <auto-generated />
using System;
using BepTroLy.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BepTroLy.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BepTroLy.API.Models.AICache", b =>
                {
                    b.Property<int>("CacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cache_id");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("cache_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("ResponseData")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("response_data");

                    b.HasKey("CacheId");

                    b.ToTable("ai_recipe_cache");
                });

            modelBuilder.Entity("BepTroLy.API.Models.ActivityLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("activity_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtraData")
                        .HasColumnType("json")
                        .HasColumnName("extra_data");

                    b.Property<int?>("FridgeId")
                        .HasColumnType("int")
                        .HasColumnName("fridge_id");

                    b.Property<int?>("RelatedItemId")
                        .HasColumnType("int")
                        .HasColumnName("related_item_id");

                    b.Property<int?>("RelatedRecipeId")
                        .HasColumnType("int")
                        .HasColumnName("related_recipe_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("activity_logs");
                });

            modelBuilder.Entity("BepTroLy.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_code");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultFreezerDays")
                        .HasColumnType("int")
                        .HasColumnName("default_freezer_days");

                    b.Property<int>("DefaultFridgeDays")
                        .HasColumnType("int")
                        .HasColumnName("default_fridge_days");

                    b.Property<int>("DefaultPantryDays")
                        .HasColumnType("int")
                        .HasColumnName("default_pantry_days");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("icon");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_vi");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("BepTroLy.API.Models.Fridge", b =>
                {
                    b.Property<int>("FridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fridge_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("FridgeId");

                    b.HasIndex("OwnerId");

                    b.ToTable("fridges");
                });

            modelBuilder.Entity("BepTroLy.API.Models.FridgeMember", b =>
                {
                    b.Property<int>("FridgeId")
                        .HasColumnType("int")
                        .HasColumnName("fridge_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("invited_at");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("FridgeId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("fridge_members");
                });

            modelBuilder.Entity("BepTroLy.API.Models.MealPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date")
                        .HasColumnName("week_end");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("meal_plans");
                });

            modelBuilder.Entity("BepTroLy.API.Models.MealPlanItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<DateTime?>("CookedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cooked_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCooked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_cooked");

                    b.Property<DateOnly>("MealDate")
                        .HasColumnType("date")
                        .HasColumnName("meal_date");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("meal_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipe_id");

                    b.HasKey("ItemId");

                    b.HasIndex("PlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("meal_plan_items");
                });

            modelBuilder.Entity("BepTroLy.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<bool>("IsSent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_sent");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at");

                    b.Property<int?>("RelatedItemId")
                        .HasColumnType("int")
                        .HasColumnName("related_item_id");

                    b.Property<string>("RelatedRecipeIds")
                        .HasColumnType("json")
                        .HasColumnName("related_recipe_ids");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("BepTroLy.API.Models.PantryItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("AddMethod")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("add_method");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("barcode");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<int?>("FridgeId")
                        .HasColumnType("int")
                        .HasColumnName("fridge_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_vi");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("UserId");

                    b.ToTable("pantry_items");
                });

            modelBuilder.Entity("BepTroLy.API.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recipe_id");

                    b.Property<int?>("AuthorUserId")
                        .HasColumnType("int")
                        .HasColumnName("author_user_id");

                    b.Property<int?>("Calories")
                        .HasColumnType("int")
                        .HasColumnName("calories");

                    b.Property<decimal?>("Carbs")
                        .HasColumnType("decimal(5, 1)")
                        .HasColumnName("carbs");

                    b.Property<int?>("CookTime")
                        .HasColumnType("int")
                        .HasColumnName("cook_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Cuisine")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cuisine");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("difficulty");

                    b.Property<decimal?>("Fat")
                        .HasColumnType("decimal(5, 1)")
                        .HasColumnName("fat");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("int")
                        .HasColumnName("favorite_count");

                    b.Property<decimal?>("Fiber")
                        .HasColumnType("decimal(5, 1)")
                        .HasColumnName("fiber");

                    b.Property<string>("Instructions")
                        .HasColumnType("json")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsDairyFree")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_dairy_free");

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_gluten_free");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_public");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_vegan");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_vegetarian");

                    b.Property<string>("MainImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("main_image_url");

                    b.Property<string>("MealTypes")
                        .HasColumnType("json")
                        .HasColumnName("meal_types");

                    b.Property<int?>("PrepTime")
                        .HasColumnType("int")
                        .HasColumnName("prep_time");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("decimal(5, 1)")
                        .HasColumnName("protein");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int")
                        .HasColumnName("rating_count");

                    b.Property<int>("Servings")
                        .HasColumnType("int")
                        .HasColumnName("servings");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("source");

                    b.Property<string>("SourceApi")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source_api");

                    b.Property<string>("Tags")
                        .HasColumnType("json")
                        .HasColumnName("tags");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleVi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title_vi");

                    b.Property<int?>("TotalTime")
                        .HasColumnType("int")
                        .HasColumnName("total_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("video_url");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("view_count");

                    b.HasKey("RecipeId");

                    b.ToTable("recipes");
                });

            modelBuilder.Entity("BepTroLy.API.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_optional");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_vi");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("quantity");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_ingredients");
                });

            modelBuilder.Entity("BepTroLy.API.Models.ShoppingList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("list_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EstimatedTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("estimated_total");

                    b.Property<int>("PurchasedItems")
                        .HasColumnType("int")
                        .HasColumnName("purchased_items");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int")
                        .HasColumnName("total_items");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ListId");

                    b.HasIndex("UserId");

                    b.ToTable("shopping_lists");
                });

            modelBuilder.Entity("BepTroLy.API.Models.ShoppingListItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<decimal?>("ActualPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("actual_price");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("EstimatedPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("estimated_price");

                    b.Property<int?>("FromRecipeId")
                        .HasColumnType("int")
                        .HasColumnName("from_recipe_id");

                    b.Property<string>("FromRecipeTitle")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("from_recipe_title");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_purchased");

                    b.Property<int>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("list_id");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_vi");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("purchased_at");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("ItemId");

                    b.HasIndex("ListId");

                    b.ToTable("shopping_list_items");
                });

            modelBuilder.Entity("BepTroLy.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Allergies")
                        .HasColumnType("json")
                        .HasColumnName("allergies");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CuisinePreferences")
                        .HasColumnType("json")
                        .HasColumnName("cuisine_preferences");

                    b.Property<string>("DietaryRestrictions")
                        .HasColumnType("json")
                        .HasColumnName("dietary_restrictions");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("ExpiryAlertDays")
                        .HasColumnType("int")
                        .HasColumnName("expiry_alert_days");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_active");

                    b.Property<bool>("NotificationEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("notification_enabled");

                    b.Property<TimeSpan?>("NotificationTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("notification_time");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("skill_level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("BepTroLy.API.Models.UserFavorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favorite_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipe_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FavoriteId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("user_favorites");
                });

            modelBuilder.Entity("BepTroLy.API.Models.UserRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rating_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Review")
                        .HasColumnType("text")
                        .HasColumnName("review");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RatingId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("user_ratings");
                });

            modelBuilder.Entity("BepTroLy.API.Models.ActivityLog", b =>
                {
                    b.HasOne("BepTroLy.API.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BepTroLy.API.Models.Fridge", b =>
                {
                    b.HasOne("BepTroLy.API.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BepTroLy.API.Models.FridgeMember", b =>
                {
                    b.HasOne("BepTroLy.API.Models.Fridge", "Fridge")
                        .WithMany("Members")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BepTroLy.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BepTroLy.API.Models.MealPlan", b =>
                {
                    b.HasOne("BepTroLy.API.Models.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BepTroLy.API.Models.MealPlanItem", b =>
                {
                    b.HasOne("BepTroLy.API.Models.MealPlan", "MealPlan")
                        .WithMany("Items")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BepTroLy.API.Models.Recipe", "Recipe")
                        .WithMany("MealPlanItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BepTroLy.API.Models.Notification", b =>
                {
                    b.HasOne("BepTroLy.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BepTroLy.API.Models.PantryItem", b =>
                {
                    b.HasOne("BepTroLy.API.Models.Category", "Category")
                        .WithMany("PantryItems")
                        .HasForeignKey("CategoryId");

                    b.HasOne("BepTroLy.API.Models.Fridge", "Fridge")
                        .WithMany("PantryItems")
                        .HasForeignKey("FridgeId");

                    b.HasOne("BepTroLy.API.Models.User", "User")
                        .WithMany("PantryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Fridge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BepTroLy.API.Models.RecipeIngredient", b =>
                {
                    b.HasOne("BepTroLy.API.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BepTroLy.API.Models.ShoppingList", b =>
                {
                    b.HasOne("BepTroLy.API.Models.User", "User")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BepTroLy.API.Models.ShoppingListItem", b =>
                {
                    b.HasOne("BepTroLy.API.Models.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("BepTroLy.API.Models.UserFavorite", b =>
                {
                    b.HasOne("BepTroLy.API.Models.Recipe", "Recipe")
                        .WithMany("Favorites")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BepTroLy.API.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BepTroLy.API.Models.UserRating", b =>
                {
                    b.HasOne("BepTroLy.API.Models.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BepTroLy.API.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BepTroLy.API.Models.Category", b =>
                {
                    b.Navigation("PantryItems");
                });

            modelBuilder.Entity("BepTroLy.API.Models.Fridge", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("PantryItems");
                });

            modelBuilder.Entity("BepTroLy.API.Models.MealPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BepTroLy.API.Models.Recipe", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Ingredients");

                    b.Navigation("MealPlanItems");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("BepTroLy.API.Models.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BepTroLy.API.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Favorites");

                    b.Navigation("MealPlans");

                    b.Navigation("Notifications");

                    b.Navigation("PantryItems");

                    b.Navigation("Ratings");

                    b.Navigation("ShoppingLists");
                });
#pragma warning restore 612, 618
        }
    }
}
